### ISSUE TITLE
Simulink Support is running slow

### ISSUE THREAD

**Issue by jmaxwell-21** [matlab-deep-learning/Pretrained-YOLOv8-Network-For-Object-Detection#9]
When I try running the yolov8SimulinkSupport model, it is running extremely slowly. It takes nearly 10 minutes from when I hit "Run" to getting an output from the simulation. My goal is to use this in a live feed in Simulink, so hopefully I can get this working fast!

**Comment by viakkala** [comment]
You might consider using the yolov8n and yolov8s models, as they are faster than other variants. 

RE>> It takes nearly 10 minutes from when I hit "Run" to getting an output from the simulation.
Typically, only the first instance will take more time due to initialization; subsequent images will process more quickly.

**Comment by anandy22** [comment]
Verified by the above suggestions given by @viakkala.
It was observed that smaller models (like yolov8n and yolov8s) had first instance run-time of ~5mins.
However, for subsequent runs the run-time comes down to less than 1min.
The above behavior was observed in R2024b (GPU configuration: - NVIDIA RTXA500(Memory:25gb and Multiprocessors:64)).

**Comment by viakkala** [comment]
Closing the issue as it's validated by @anandy22.
